### ISSUE TITLE
The publish example code cannot be executed.

### ISSUE THREAD

**Issue by kang-seongbeom** [DLHub-Argonne/dlhub_sdk#110]
After receiving the file from site https://github.com/ryanchard/dlhub_publish_example, I am trying to publish it  through the sdk. but, I am getting the error 'client.publish_servable(model)'. The error code is 'jsonschema.exceptions.ValidationError: 'type' is a required property'. Please tell me why the error occurs

**Comment by WardLT** [comment]
Thanks for reaching out! This example is very out of date with our new infrastructure. I think the error is that our schema has changed since we created this repository, and the [`dlhub.json`](https://github.com/ryanchard/dlhub_publish_example/blob/master/dlhub.json) is no longer valid with our new schemas.

Could you try some of the examples here? https://github.com/DLHub-Argonne/dlhub_sdk/tree/master/examples 

@ryanchard , should we remove your example repo?

**Comment by ryanchard** [comment]
Oh, yes, that is very out of date. I've set the repo to private so we don't stumble into it again. Was this linked somewhere in the docs? If so we should remove it.
